#   IMPLEMENTATION OF HYPOTHESIS TEST FOR DELTA DISTRIBUTION

#   import delta power data generated by grpRuns_1.0.1.ipynb
dir = "/Users/joshuaighalo/Documents/BrainNet/Projects/Workspace/Results/Music Therapy/BandPower/1.0.1/"  
chansMean = read.csv(paste(dir,"meanChannels.csv",sep=""), header=FALSE)
delta = read.csv(paste(dir,"delta.csv",sep=""), header=FALSE)


#   data prepraration and manipulation

##  generate alphabetical categories to represent pre and post therapy
group_pre = rep('pre', 5) 
group_post = rep('post', 5)

##   seperate data into pre and post per groups
m11_chansMean = chansMean[2:6,("V1")]
c11_chansMean = chansMean[7:11,("V1")]
m12_chansMean = chansMean[2:6,("V2")]
c12_chansMean = chansMean[7:11,("V2")]
m21_chansMean = chansMean[2:6,("V3")]
c21_chansMean = chansMean[7:11,("V3")]
m22_chansMean = chansMean[2:6,("V4")]
c22_chansMean = chansMean[7:11,("V4")]
m11_TP9 = delta[2:6,("V1")]
c11_TP9 = delta[7:11,("V1")]
m12_TP9 = delta[2:6,("V2")]
c12_TP9 = delta[7:11,("V2")]
m21_TP9 = delta[2:6,("V3")]
c21_TP9 = delta[7:11,("V3")]
m22_TP9 = delta[2:6,("V4")]
c22_TP9 = delta[7:11,("V4")]
m11_AF7 = delta[2:6,("V5")]
c11_AF7 = delta[7:11,("V5")]
m12_AF7 = delta[2:6,("V6")]
c12_AF7 = delta[7:11,("V6")]
m21_AF7 = delta[2:6,("V7")]
c21_AF7 = delta[7:11,("V7")]
m22_AF7 = delta[2:6,("V8")]
c22_AF7 = delta[7:11,("V8")]
m11_AF8 = delta[2:6,("V9")]
c11_AF8 = delta[7:11,("V9")]
m12_AF8 = delta[2:6,("V10")]
c12_AF8 = delta[7:11,("V10")]
m21_AF8 = delta[2:6,("V11")]
c21_AF8 = delta[7:11,("V11")]
m22_AF8 = delta[2:6,("V12")]
c22_AF8 = delta[7:11,("V12")]
m11_TP10 = delta[2:6,("V13")]
c11_TP10 = delta[7:11,("V13")]
m12_TP10 = delta[2:6,("V14")]
c12_TP10 = delta[7:11,("V14")]
m21_TP10 = delta[2:6,("V15")]
c21_TP10 = delta[7:11,("V15")]
m22_TP10 = delta[2:6,("V16")]
c22_TP10 = delta[7:11,("V16")]

##   merge data into one dataframe
m1_chansMean = rbind(cbind(m11_chansMean,group_pre),cbind(m12_chansMean,group_post))
m2_chansMean = rbind(cbind(m21_chansMean,group_pre),cbind(m22_chansMean,group_post))
c1_chansMean = rbind(cbind(c11_chansMean,group_pre),cbind(c12_chansMean,group_post))
c2_chansMean = rbind(cbind(c21_chansMean,group_pre),cbind(c22_chansMean,group_post))
m1_TP9 = rbind(cbind(m11_TP9,group_pre),cbind(m12_TP9,group_post))
m2_TP9 = rbind(cbind(m21_TP9,group_pre),cbind(m22_TP9,group_post))
c1_TP9 = rbind(cbind(c11_TP9,group_pre),cbind(c12_TP9,group_post))
c2_TP9 = rbind(cbind(c21_TP9,group_pre),cbind(c22_TP9,group_post))
m1_AF7 = rbind(cbind(m11_AF7,group_pre),cbind(m12_AF7,group_post))
m2_AF7 = rbind(cbind(m21_AF7,group_pre),cbind(m22_AF7,group_post))
c1_AF7 = rbind(cbind(c11_AF7,group_pre),cbind(c12_AF7,group_post))
c2_AF7 = rbind(cbind(c21_AF7,group_pre),cbind(c22_AF7,group_post))
m1_AF8 = rbind(cbind(m11_AF8,group_pre),cbind(m12_AF8,group_post))
m2_AF8 = rbind(cbind(m21_AF8,group_pre),cbind(m22_AF8,group_post))
c1_AF8 = rbind(cbind(c11_AF8,group_pre),cbind(c12_AF8,group_post))
c2_AF8 = rbind(cbind(c21_AF8,group_pre),cbind(c22_AF8,group_post))
m1_TP10 = rbind(cbind(m11_TP10,group_pre),cbind(m12_TP10,group_post))
m2_TP10 = rbind(cbind(m21_TP10,group_pre),cbind(m22_TP10,group_post))
c1_TP10 = rbind(cbind(c11_TP10,group_pre),cbind(c12_TP10,group_post))
c2_TP10 = rbind(cbind(c21_TP10,group_pre),cbind(c22_TP10,group_post))

##   change headers of each matrices generated above
colnames(m1_chansMean) <- c("power","group")
colnames(m2_chansMean) <- c("power","group")
colnames(c1_chansMean) <- c("power","group")
colnames(c2_chansMean) <- c("power","group")
colnames(m1_TP9) <- c("power","group")
colnames(m2_TP9) <- c("power","group")
colnames(c1_TP9) <- c("power","group")
colnames(c2_TP9) <- c("power","group")
colnames(m1_AF7) <- c("power","group")
colnames(m2_AF7) <- c("power","group")
colnames(c1_AF7) <- c("power","group")
colnames(c2_AF7) <- c("power","group")
colnames(m1_AF8) <- c("power","group")
colnames(m2_AF8) <- c("power","group")
colnames(c1_AF8) <- c("power","group")
colnames(c2_AF8) <- c("power","group")
colnames(m1_TP10) <- c("power","group")
colnames(m2_TP10) <- c("power","group")
colnames(c1_TP10) <- c("power","group")
colnames(c2_TP10) <- c("power","group")


#   perform shapiro-wilk test for normality on this vector of values
#   Criteria for Normality Test: https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/basic-statistics/summary-statistics/normality-test/before-you-start/data-considerations/
#   data-task-timepoint
data_11 = as.numeric(c(cbind(m11_chansMean,c11_chansMean,m11_TP9,c11_TP9,m11_AF7,c11_AF7,m11_AF8,c11_AF8,m11_TP10,c11_TP10)))
data_12 = as.numeric(c(cbind(m12_chansMean,c12_chansMean,m12_TP9,c12_TP9,m12_AF7,c12_AF7,m12_AF8,c12_AF8,m12_TP10,c12_TP10)))
data_21 = as.numeric(c(cbind(m21_chansMean,c21_chansMean,m21_TP9,c21_TP9,m21_AF7,c21_AF7,m21_AF8,c21_AF8,m21_TP10,c21_TP10)))
data_22 = as.numeric(c(cbind(m22_chansMean,c22_chansMean,m22_TP9,c22_TP9,m22_AF7,c22_AF7,m22_AF8,c22_AF8,m22_TP10,c22_TP10)))

normality_Task1 = as.numeric(data_12) - as.numeric(data_11)
normality_Task1 = shapiro.test(normality_Task1)
print(normality_Task1)
normality_Task1 = normality_Task1$p.value

normality_Task2 = as.numeric(data_22) - as.numeric(data_21)
normality_Task2 = shapiro.test(normality_Task2)
print(normality_Task2)
normality_Task2 = normality_Task2$p.value


#   run T-test
parametricTest = function(data,value,pairs,normValue,varName){
    if (normValue > 0.05){
    # Paired t.Test: assume data is normally distributed
       outcome= t.test(as.numeric(value)~pairs,data=data,paired=TRUE)
       print(paste("t.test:",varName,outcome$p.value))
       return (outcome$p.value)
    }
    if (normValue < 0.05){
    # Wilcoxon Signed Rank Test: assume data is not normally distributed
        outcome= wilcox.test(as.numeric(data[,value])~data[,pairs],data=data,paired=TRUE)
        print(paste("wilcox.test:",varName,outcome$p.value))
        return (outcome$p.value)
    }
}

parametricTest(m1_chansMean,"power","group",normality_Task1,'m1_chansMean:')
parametricTest(m2_chansMean,"power","group",normality_Task2,'m2_chansMean:')
parametricTest(c1_chansMean,"power","group",normality_Task1,'c1_chansMean:')
parametricTest(c2_chansMean,"power","group",normality_Task2,'c2_chansMean:')
parametricTest(m1_TP9,"power","group",normality_Task1,'m1_TP9:')
parametricTest(m2_TP9,"power","group",normality_Task2,'m2_TP9:')
parametricTest(c1_TP9,"power","group",normality_Task1,'c1_TP9:')
parametricTest(c2_TP9,"power","group",normality_Task2,'c2_TP9:')
parametricTest(m1_AF7,"power","group",normality_Task1,'m1_AF7:')
parametricTest(m2_AF7,"power","group",normality_Task2,'m2_AF7:')
parametricTest(c1_AF7,"power","group",normality_Task1,'c1_AF7:')
parametricTest(c2_AF7,"power","group",normality_Task2,'c2_AF7:')
parametricTest(m1_AF8,"power","group",normality_Task1,'m1_AF8:')
parametricTest(m2_AF8,"power","group",normality_Task2,'m2_AF8:')
parametricTest(c1_AF8,"power","group",normality_Task1,'c1_AF8:')
parametricTest(c2_AF8,"power","group",normality_Task2,'c2_AF8:')
parametricTest(m1_TP10,"power","group",normality_Task1,'m1_TP10:')
parametricTest(m2_TP10,"power","group",normality_Task2,'m2_TP10:')
parametricTest(c1_TP10,"power","group",normality_Task1,'c1_TP10:')
parametricTest(c2_TP10,"power","group",normality_Task2,'c2_TP10:')




